// <auto-generated />
namespace Proiect_Rent_A_Car.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedListingOrderExtras : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedListingOrderExtras));
        
        string IMigrationMetadata.Id
        {
            get { return "202401041541469_Added Listing Order Extras"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
