// <auto-generated />
namespace Proiect_Rent_A_Car.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addorder1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addorder1));
        
        string IMigrationMetadata.Id
        {
            get { return "202401071321223_add order#1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
